mod 'boxen', '3.3.4', :github_tarball => 'boxen/puppet-boxen'
mod 'stdlib', '4.0.0', :github_tarball => "puppetlabs/puppetlabs-stdlib"
mod 'homebrew', '1.6.1', :github_tarball => 'boxen/puppet-homebrew'
mod 'repository', '2.3.0', :github_tarball => 'boxen/puppet-repository'
